#!/usr/bin/env bash

module load gatk/4.1.2.0

#gatk HaplotypeCaller \
#    -R reference.fasta \
#    -I sample1.bam \
#    -O variants.g.vcf \
#    -ERC GVCF
# https://software.broadinstitute.org/gatk/documentation/article?id=11050

gatk HaplotypeCaller \
    -R reference.fasta \
    -I sample1.bam \
    -O variants.g.vcf \
    -ERC GVCF
