#!/usr/bin/env bash

module load gatk/4.1.2.0

# https://software.broadinstitute.org/gatk/documentation/article?id=11050
# https://gatkforums.broadinstitute.org/gatk/discussion/1601/how-can-i-prepare-a-fasta-file-to-use-as-reference

#module load picard/2.20.6
#To execute picard run: java -jar $EBROOTPICARD/picard.jar

# java -jar $EBROOTPICARD/CreateSequenceDictionary.jar R= projects/def-msteiner/readdepth/ref_genome/hg19.fa O= hg19.dict

# samtools view -H scratch/subsets/files/HuRef.82x.subsampled10x.bam | head
# What's the best way to create a subset of my BAM file containing only reads over a small interval?
# java -jar GenomeAnalysisTK.jar -R reference.fasta -I full_input.bam -T PrintReads -L chr1:10-20 -o subset_input.bam
# java -jar $EBROOTPICARD/picard.jar BuildBamIndex I=scratch/subsets/files/HuRef.82x.subsampled10x.bam



module load picard/2.20.6
java -jar $EBROOTPICARD/picard.jar BuildBamIndex I=scratch/subsets/files/HuRef.82x.subsampled10x.bam

gatk HaplotypeCaller \
    -R /projects/def-msteiner/readdepth/ref_genome/human_g1k_v37.fasta \
    -I /scratch/subsets/files/HuRef.82x.subsampled10x.bam \
    -O /scratch/HuRef10x.vcf \

#gatk HaplotypeCaller -R projects/def-msteiner/readdepth/ref_genome/human_g1k_v37.fasta -I scratch/subsets/files/HuRef.82x.subsampled10x.bam -O scratch/HuRef10x.vcf

#Exception in thread "main" 
