#!/usr/bin/env bash
#SBATCH --nodes=4
#SBATCH --time=1-00:00

module load gatk/4.1.2.0

files=(10)

for file in ${files[@]}; do

#use gatk HaplotypeCaller
gatk HaplotypeCaller \
    -R projects/def-msteiner/readdepth/ref_genome/human_g1k_v37.fasta \
    -I scratch/subsets/files/HuRef.82x.subsampled${file}x.bam \
    -O scratch/HuRef${file}x.vcf \

echo 'HuRef.82x.subsampled${file}x.bam'

done
