#!/usr/bin/env bash

module load gatk/4.1.2.0
module load picard/2.20.6

files=(5 15 25 35 45)

for file in ${files[@]}; do

#index BAM file
java -jar $EBROOTPICARD/picard.jar BuildBamIndex I=scratch/subsets/files/HuRef.82x.subsampled${file}x.bam

    
echo 'HuRef.82x.subsampled${file}x.bam indexed'

done

