#!/usr/bin/env bash

module load gcc/7.3.0
module load samtools/1.9

fraction=(122 244 3658 4878 6098 7317 8537)
depth=(10 20 30 40 50 60 70)

for i in ${!depth[*]}
do
samtools view -s 1.${fraction[$i]} projects/def-msteiner/readdepth/BAM/HuRef.82x.bam -o projects/def-msteiner/sngo/HuRef.82x.subsampled${depth[$i]}x.bam
echo "HuRef.82x.subsampled${depth[$i]}x.bam"
done
